--unlock account lbacsys
--Dang nhap vao oracle bang tai khoan sys, su dung container xepdb1
CREATE USER COMPANY IDENTIFIED BY 123;
GRANT LBAC_DBA TO COMPANY;
GRANT ALL PRIVILEGES TO COMPANY;

ALTER PLUGGABLE DATABASE xepdb1 OPEN READ WRITE;
ALTER SESSION SET CONTAINER = xepdb1;

SELECT * FROM dba_ols_status;--kiem tra trang thai ols

--cau hinh va kich hoat ols tren xepdb1

connect sys/301791466 as sysdba;
EXEC LBACSYS.CONFIGURE_OLS;
/
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; 
disconnect;
/
--EXECUTE SA_SYSDBA.DROP_POLICY('ESBD');
D--ROP TABLE ANNOUNCEMENTS;

CONNECT COMPANY/123;--duoc gan role lbac_dba
DROP TABLE ANNOUNCEMENTS;
CREATE TABLE ANNOUNCEMENTS (MESSAGE VARCHAR2(4000)); --tao bang thong bao thanh cong

BEGIN
SA_SYSDBA.CREATE_POLICY('ESBD', 'ROWLABEL');
END;--tao chinh sach thanh cong
DISCONNECT;

/
--GÁN QUYỀN CHO QUẢN TRỊ VIÊN
CONNECT LBACSYS/lbacsys;

show con_name;
GRANT ESBD_DBA TO COMPANY; --grant success;
GRANT EXECUTE ON SA_COMPONENTS TO COMPANY; --grant success;
GRANT EXECUTE ON SA_LABEL_ADMIN TO COMPANY; --grant success;
GRANT EXECUTE ON SA_POLICY_ADMIN TO COMPANY; --grant success;
GRANT EXECUTE ON SA_USER_ADMIN TO COMPANY; --grant success;
GRANT EXECUTE ON CHAR_TO_LABEL TO COMPANY; --grant success;
DISCONNECT;

/
--TẠO LEVEL
CONNECT COMPANY/123;

BEGIN SA_COMPONENTS.CREATE_LEVEL (
    POLICY_NAME => 'ESBD',
    LONG_NAME => 'GIAM DOC',
    SHORT_NAME => 'GD',
    LEVEL_NUM => 9000
);
END;
/
BEGIN SA_COMPONENTS.CREATE_LEVEL
(POLICY_NAME => 'ESBD',
LONG_NAME => 'TRUONG PHONG',
SHORT_NAME => 'TP',
LEVEL_NUM => 8000);
END;
/
BEGIN SA_COMPONENTS.CREATE_LEVEL
(POLICY_NAME => 'ESBD',
LONG_NAME => 'NHAN VIEN',
SHORT_NAME => 'NV',
LEVEL_NUM => 7000);
END;
/
DISCONNECT;
--TAO LEVEL THANH CONG
/
--TẠO COMPARTMENT
CONNECT COMPANY/123;

BEGIN SA_COMPONENTS.CREATE_COMPARTMENT
(POLICY_NAME => 'ESBD',
LONG_NAME => 'MUA BAN',
short_name => 'MB',
COMP_NUM => 100);
END;
/
BEGIN SA_COMPONENTS.CREATE_COMPARTMENT
(POLICY_NAME => 'ESBD',
LONG_NAME => 'SAN XUAT',
SHORT_NAME => 'SX',
COMP_NUM => 200);
END;
/
BEGIN SA_COMPONENTS.CREATE_COMPARTMENT
(POLICY_NAME => 'ESBD',
LONG_NAME => 'GIA CONG',
SHORT_NAME => 'GC',
COMP_NUM => 300);
END;
/
DISCONNECT;
--TAO COMPARTNENT THANH CONG
/
-- TẠO GROUP
CONNECT COMPANY/123

BEGIN SA_COMPONENTS.CREATE_GROUP
(POLICY_NAME => 'ESBD',
LONG_NAME => 'TAP DOAN S',
SHORT_NAME => 'S',
GROUP_NUM => 1,
PARENT_NAME => NULL);
END;
/
BEGIN SA_COMPONENTS.CREATE_GROUP
(POLICY_NAME => 'ESBD',
LONG_NAME => 'MIEN BAC',
SHORT_NAME => 'B',
GROUP_NUM => 10,
PARENT_NAME => 'S');
END;
/
BEGIN SA_COMPONENTS.CREATE_GROUP
(POLICY_NAME => 'ESBD',
LONG_NAME => 'MIEN TRUNG',
SHORT_NAME => 'T',
GROUP_NUM => 20,
PARENT_NAME => 'S');
END;
/
BEGIN SA_COMPONENTS.CREATE_GROUP
(POLICY_NAME => 'ESBD',
LONG_NAME => 'MIEN NAM',
SHORT_NAME => 'N',
GROUP_NUM => 30,
PARENT_NAME => 'S');
END;
/
DISCONNECT;
--TAO GROUP THANH CONG
--------------------------------------------------------------------------------
-- SX:1, GC:2, MB:3
-- B:1, T:2, N:3
/
CONNECT COMPANY/123;
/
--AP DUNG CHINH SACH OLS LEN BANG THONG BAO
BEGIN SA_POLICY_ADMIN.REMOVE_TABLE_POLICY
(POLICY_NAME => 'ESBD',
SCHEMA_NAME => 'COMPANY',
TABLE_NAME => 'ANNOUNCEMENTS');
END;
/
DISCONNECT;
/
--GAN CHINH SACH BAN DAU CHO BANG DE GAN LABEL CHO DU LIEU 
CONNECT COMPANY/123;
BEGIN SA_POLICY_ADMIN.APPLY_TABLE_POLICY
(POLICY_NAME => 'ESBD',
SCHEMA_NAME => 'COMPANY',
TABLE_NAME => 'ANNOUNCEMENTS',
TABLE_OPTIONS => 'NO_CONTROL');
END;
/
--TẠO NHÃN (CAU A)
CONNECT COMPANY/123;

BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 2630,
label_value     => 'TP:MB,SX,GC:N');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 3000,
label_value     => 'GD');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 2000,
label_value     => 'TP');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 1000,
label_value     => 'NV');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 2130,
label_value     => 'TP:SX:N');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 2120,
label_value     => 'TP:SX:T');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 3010,
label_value     => 'GD:MB,SX,GC:B');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 2010,
label_value     => 'TP:MB,SX,GC:B');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 1030,
label_value     => 'NV:MB,SX,GC:N');
END;
/
CONNECT COMPANY/123;
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 1660,
label_value     => 'TP:MB,SX,GC:B,T,N');
END;
/
CONNECT COMPANY/123;
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 1130,
label_value     => 'NV:SX:N');
END;
/
BEGIN SA_LABEL_ADMIN.CREATE_LABEL 
(policy_name     => 'ESBD',
label_tag       => 3660,
label_value     => 'GD:MB,SX,GC:B,T,N');
END;
DISCONNECT;
-- TAO NHAN THANH CONG
/
-----------------------------------------------------------------------------
--THEM THONG BAO 
connect COMPANY/123;
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui GIAM DOC:...',CHAR_TO_LABEL('ESBD','GD'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui giam doc mien Bac:...',CHAR_TO_LABEL('ESBD','GD:SX,GC,MB:B'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui TRUONG PHONG:...',CHAR_TO_LABEL('ESBD','TP'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui NHAN VIEN:...',CHAR_TO_LABEL('ESBD','NV'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui TRUONG PHONG SX MIEN NAM:...',CHAR_TO_LABEL('ESBD','TP:SX:N'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui TRUONG PHONG SX MIEN TRUNG:...',CHAR_TO_LABEL('ESBD','TP:SX:T'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao t1:...',CHAR_TO_LABEL('ESBD','TP'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao t2:...',CHAR_TO_LABEL('ESBD','TP:SX:T'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui TRUONG PHONG MIEN BAC:...',CHAR_TO_LABEL('ESBD','TP:SX:T'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui NHAN VIEN MIEN NAM:...',CHAR_TO_LABEL('ESBD','NV:SX,GC,MB:N'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui NHAN VIEN SAN XUAT MIEN NAM:...',CHAR_TO_LABEL('ESBD','NV:SX:N'));
INSERT INTO ANNOUNCEMENTS VALUES ('Thong bao gui TRUONG PHONG MIEN NAM:...',CHAR_TO_LABEL('ESBD','TP:SX,GC,MB:N'));
-----------------------------------------------------------------------------

/

DISCONNECT;
/
--XOA CHINH SACH OLS LEN BANG THONG BAO
CONNECT COMPANY/123;
BEGIN SA_POLICY_ADMIN.REMOVE_TABLE_POLICY
(POLICY_NAME => 'ESBD',
SCHEMA_NAME => 'COMPANY',
TABLE_NAME => 'ANNOUNCEMENTS');
END;
/
DISCONNECT;
/
--AP DUNG CHINH SACH OLS LEN BANG THONG BAO
CONNECT COMPANY/123;
BEGIN SA_POLICY_ADMIN.APPLY_TABLE_POLICY
(POLICY_NAME => 'ESBD',
SCHEMA_NAME => 'COMPANY',
TABLE_NAME => 'ANNOUNCEMENTS',
TABLE_OPTIONS => 'READ_CONTROL, CHECK_CONTROL',
PREDICATE => NULL);
END;
/
--------------------------------TAO USER----------------------------------------
CREATE USER GIAMDOC IDENTIFIED BY giamdoc;
GRANT CREATE SESSION TO GIAMDOC;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO GIAMDOC;

CREATE USER TRUONGPHONG IDENTIFIED BY truongphong;
GRANT CREATE SESSION TO TRUONGPHONG;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO TRUONGPHONG;

CREATE USER NHANVIEN IDENTIFIED BY nhanvien;
GRANT CREATE SESSION TO NHANVIEN;
GRANT SELECT ON company.ANNOUNCEMENTS TO NHANVIEN;

CREATE USER TPSXMN IDENTIFIED BY tpsxmn;
GRANT CREATE SESSION TO TPSXMN;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO TPSXMN;

CREATE USER TPSXMT IDENTIFIED BY tpsxmt;
GRANT CREATE SESSION TO TPSXMT;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO TPSXMT;

CREATE USER GIAMDOCMB IDENTIFIED BY giamdocmb;
GRANT CREATE SESSION TO GIAMDOCMB;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO GIAMDOCMB;

CREATE USER NHANVIEN_MN IDENTIFIED BY nhanvienmn;
GRANT CREATE SESSION TO NHANVIEN_MN;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO NHANVIEN_MN;

CREATE USER NHANVIEN_SX_MN IDENTIFIED BY nhanviensxmn;
GRANT CREATE SESSION TO NHANVIEN_SX_MN;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO NHANVIEN_SX_MN;
/
CREATE USER TRUONGPHONG_MN IDENTIFIED BY truongphongmn;
GRANT CREATE SESSION TO TRUONGPHONG_MN;
GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO TRUONGPHONG_MN;
--GRANT SELECT ON COMPANY.ANNOUNCEMENTS TO NV060;
/
CONNECT COMPANY/123;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'TRUONGPHONG_MN',
MAX_READ_LABEL => 'TP:MB,SX,GC:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV038',
MAX_READ_LABEL => 'TP:MB,SX,GC:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV039',
MAX_READ_LABEL => 'TP:MB,SX,GC:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NHANVIEN_SX_MN',
MAX_READ_LABEL => 'NV:SX:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV046',
MAX_READ_LABEL => 'NV:SX:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV047',
MAX_READ_LABEL => 'NV:SX:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'GIAMDOC',
MAX_READ_LABEL => 'GD:MB,SX,GC:B,T,N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV000',
MAX_READ_LABEL => 'GD:MB,SX,GC:B,T,N');
END;
/
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'GIAMDOC','READ');
CONNECT COMPANY/123;
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'TRUONGPHONG',
MAX_READ_LABEL => 'TP:MB,SX,GC:B,T,N');
END;
/
BEGIN
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV040',
MAX_READ_LABEL => 'TP:MB,SX,GC:B,T,N');
END;
/

BEGIN
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV043',
MAX_READ_LABEL => 'TP:MB,SX,GC:B,T,N');
END;
/
BEGIN
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV044',
MAX_READ_LABEL => 'TP:MB,SX,GC:B,T,N');
END;
/
BEGIN
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV045',
MAX_READ_LABEL => 'TP:MB,SX,GC:B,T,N');
END;
/
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'TP','READ');
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NHANVIEN',
MAX_READ_LABEL => 'NV');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV100',
MAX_READ_LABEL => 'NV');
END;
/
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'NV','READ');
/
DISCONNECT;
/
CONNECT COMPANY/123;
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'TPSXMN',
MAX_READ_LABEL => 'TP:SX:N');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV041',
MAX_READ_LABEL => 'TP:SX:N');
END;
/
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'TPSXMN','READ');
/
CONNECT COMPANY/123;
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'TPSXMT',
MAX_READ_LABEL => 'TP:SX:T');
END;
/

BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV042',
MAX_READ_LABEL => 'TP:SX:T');
END;
/
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'TPSXMT','READ');
/
DISCONNECT;
/
CONNECT COMPANY/123;
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'GIAMDOCMB',
MAX_READ_LABEL => 'GD:MB,SX,GC:B');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV001',
MAX_READ_LABEL => 'GD:MB,SX,GC:B');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV002',
MAX_READ_LABEL => 'GD:MB,SX,GC:B');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV003',
MAX_READ_LABEL => 'GD:MB,SX,GC:B');
END;
/
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV004',
MAX_READ_LABEL => 'GD:MB,SX,GC:B');
END;
--EXEC SA_USER_ADMIN.SET_USER_PRIVS('ESBD', 'GIAMDOCMB','READ');
/
CONNECT COMPANY/123;
BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NHANVIEN_MN',
MAX_READ_LABEL => 'NV:MB,SX,GC:N');
END;
/
DISCONNECT;

BEGIN 
SA_USER_ADMIN.SET_USER_LABELS
(POLICY_NAME => 'ESBD', 
USER_NAME => 'NV048',
MAX_READ_LABEL => 'NV:MB,SX,GC:N');
END;
/
DISCONNECT;
/
SELECT * FROM COMPANY.ANNOUNCEMENTS;
/
GRANT SELECT ON company.ANNOUNCEMENTS TO PUBLIC;
/
--SELECT COMP_NAME, STATUS FROM DBA_REGISTRY WHERE COMP_ID='OLS';
--connect COMPANY/123;
--SELECT * FROM LBACSYS.dba_ols_users;
--
--
--CONNECT COMPANY/123;
SELECT * FROM all_sa_labels;
select * from all_sa_data_labels;
select * from all_sa_user_labels;
select * from all_sa_policies;
SELECT * FROM all_sa_table_policies;
--
--CONNECT COMPANY/123;
--select * from all_sa_levels;
--select * from all_sa_compartments;
--select * from all_sa_groups;


