ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';  
--ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE; 
BEGIN
    EXECUTE IMMEDIATE 'DROP  USER COMPANY CASCADE';
EXCEPTION 
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('User is not exists');
END;
/

CREATE USER COMPANY IDENTIFIED BY 123;
/
GRANT ALL PRIVILEGES TO COMPANY;
GRANT ALTER SESSION TO COMPANY;
GRANT SELECT ON DBA_ROLES TO COMPANY;
GRANT SELECT  ANY DICTIONARY TO COMPANY;
GRANT CONNECT, RESOURCE TO COMPANY WITH ADMIN OPTION;
GRANT DBA TO COMPANY WITH ADMIN OPTION;
GRANT SELECT ON DBA_USERS TO COMPANY WITH GRANT OPTION;
GRANT CREATE USER TO COMPANY WITH ADMIN OPTION;
GRANT DROP USER TO COMPANY WITH ADMIN OPTION;
GRANT CREATE SESSION TO COMPANY;
GRANT EXECUTE ON DBMS_RLS TO COMPANY;
GRANT ALTER SYSTEM TO COMPANY;
GRANT AUDIT_ADMIN TO COMPANY;
GRANT AUDIT_VIEWER TO COMPANY;
GRANT SELECT  ON UNIFIED_AUDIT_TRAIL TO COMPANY;
GRANT EXECUTE ON dbms_fga TO COMPANY;
GRANT EXECUTE ON DBMS_CRYPTO TO COMPANY;
COMMIT;
/



